buildingspy/development/merger.py
when reading paths from a file with one path per line,
this should fix #56
=> normalize newline and dir separator 

buildingspy/examples/dymola/case1/.gitignore, buildingspy/examples/dymola/case2/.gitignore, buildingspy/examples/dymola/runSimulationTranslated.py, buildingspy/simulate/Simulator.py
adapted `runSimulationTranslated.py` according to `runSimulation.py`
=> Issue70 simulation

buildingspy/development/validator.py
=> detect single line HTML,

buildingspy/simulate/Simulator.py
I added some parenthesis to print statements in Simulator.py to make them compatible with Python 2 and 3
I also replaced the 'has_key' method for the same reason
=> Compatibility with Python 3

buildingspy/development/regressiontest.py, buildingspy/tests/test_development_merger.py, buildingspy/tests/test_simulate_Simulator.py
This is the result from running
```
2to3.py -wn -f print regressiontest.py
```
This should not break anything, `print()` works in Python2 and Python3
The 2to3 script knows some more rules:
https://docs.python.org/3/library/2to3.html
=> print() function with parantheses

buildingspy/development/merger.py, buildingspy/simulate/Simulator.py
=> Spyder claims these modules are never used

.travis.yml
- set matplotlib environment variable from travis file, not from web interface
- also run selected doctests
=> Travis doctest

buildingspy/development/error_dictionary.py, buildingspy/development/merger.py, buildingspy/development/refactor.py, buildingspy/development/regressiontest.py, buildingspy/development/unittest.py, buildingspy/development/validator.py, buildingspy/examples/dymola/plotResult.py, buildingspy/examples/dymola/runSimulation.py, buildingspy/examples/dymola/runSimulationTranslated.py, buildingspy/io/outputfile.py, buildingspy/io/postprocess.py, buildingspy/io/reporter.py, buildingspy/simulate/Simulator.py, buildingspy/tests/test_development_Validator.py, buildingspy/tests/test_development_error_dictionary.py, buildingspy/tests/test_development_merger.py, buildingspy/tests/test_development_refactor.py, buildingspy/tests/test_development_regressiontest.py, buildingspy/tests/test_examples_dymola.py, buildingspy/tests/test_io_outputfile.py, buildingspy/tests/test_io_postprocess.py, buildingspy/tests/test_simulate_Simulator.py
this is for #94 and should not break anything
not yet using unicode_literals
```python
blankline
from __future__ import
blankline
from builtins import
blankline
import other packages os, sys, numpy
```
=> importing from future in every file to prevent regressions

buildingspy/development/merger.py
=> added fix for running merger script for other libraries than annex60

buildingspy/development/deleteReferenceResults.py, buildingspy/development/fixParameters.py, buildingspy/development/matchParameters.py
Hi Thierry @tsnouidui,
I updated your new script to always use print() as a function with parantheses, not as a statement, in order to make it possibly Python 3 compatible (also see #94).
This should not break anything, but I did not test it thoroughly.
Could you test it, too, and if it works for you, merge the update into your branch? Thanks.
=> update fixParameter to use print() function

buildingspy/simulate/Simulator.py
Python 3 compatible fix to issue #102
=> Issue102 string parameters

buildingspy/development/regressiontest.py
Merge https://github.com/lbl-srg/BuildingsPy/pull/123 after CI passes
=> Thorade str find

buildingspy/development/regressiontest.py
str type has the find method builtin
https://docs.python.org/2/library/stdtypes.html#str.find
https://docs.python.org/3/library/stdtypes.html#str.find
=> do not import string,

buildingspy/development/merger.py, buildingspy/development/refactor.py, buildingspy/development/regressiontest.py, buildingspy/development/validator.py, buildingspy/io/outputfile.py, buildingspy/io/reporter.py, buildingspy/tests/test_examples_dymola.py
test.test_support has been renamed to test.support on Python3
https://docs.python.org/2.7/library/test.html#module-test.test_support
=> test.test_support is test.support

buildingspy/development/merger.py, buildingspy/development/refactor.py, buildingspy/development/regressiontest.py, buildingspy/development/validator.py, buildingspy/io/outputfile.py, buildingspy/io/reporter.py, buildingspy/tests/test_examples_dymola.py
Integration testing for https://github.com/lbl-srg/BuildingsPy/pull/135
=> Thorade test support

buildingspy/development/validator.py, buildingspy/tests/test_development_Validator.py
=> Refactored for #155

buildingspy/development/merger.py
=> Added additional files to exclude list

Makefile, buildingspy/development/regressiontest.py, buildingspy/tests/MyModelicaLibrary/Examples/FMUs/Integrator_Underscore.mo, buildingspy/tests/MyModelicaLibrary/Examples/FMUs/package.order, buildingspy/tests/MyModelicaLibrary/Resources/ReferenceResults/Dymola/MyModelicaLibrary_Examples_FMUs_Integrator_Underscore.txt, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/Dymola/Examples/FMUs/Integrator_Underscore.mos, buildingspy/tests/test_development_regressiontest.py
=> Issue153 include fmu

Makefile, buildingspy/development/error_dictionary.py, buildingspy/development/regressiontest.py, buildingspy/development/validator.py, buildingspy/io/postprocess.py, buildingspy/simulate/Simulator.py, buildingspy/tests/test_simulate_Simulator.py
These are some selected changes from running
```
autopep8 --in-place --recursive --max-line-length=100 --exclude="*/thirdParty/*" --ignore="E402,F401,F403,F405" --aggressive --aggressive --aggressive buildingspy
```
=> autopep8 aggressive

.travis.yml, README.rst
and not for the last build over all branches
=> show badge for master branch

buildingspy/development/refactor.py
=> Issue170 move class images

.gitignore
https://www.jetbrains.com/pycharm/
https://blogs.msdn.microsoft.com/visualstudio/2017/05/12/a-lap-around-python-in-visual-studio-2017/
https://docs.microsoft.com/en-us/visualstudio/python/python-environments
=> ignore files created by PyCharm or VisualStudio

.travis.yml, buildingspy/development/regressiontest.py, buildingspy/io/postprocess.py
this should close #174
no whitespace after comma, only after colon
https://stackoverflow.com/questions/16311562/python-json-without-whitespaces
Note: for Python>=3.4 this is the default
and it addresses parts of #175 
json dumps are sorted by key
=> nicer json.dumps

buildingspy/fmi/__init__.py
=> Excluded CPUtime and EventCounter from list of dependencies

.travis.yml, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/usr/local/bin/dymola
=> Updated dockerfile

.travis.yml, MANIFEST.in, buildingspy/development/jmodelica_run.template, buildingspy/development/jmodelica_run_all.template, buildingspy/development/regressiontest.py, buildingspy/development/validator.py, buildingspy/examples/dymola/plotResult.py, buildingspy/io/postprocess.py, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/usr/local/bin/jm_ipython.sh, buildingspy/tests/test_development_Validator.py, buildingspy/tests/test_development_merger.py, buildingspy/tests/test_development_regressiontest.py, setup.py
This merges the JModelica testing.
More tests will be added later.
=> Issue184 jmodelica regression testing

buildingspy/CHANGES.txt, buildingspy/development/refactor.py, buildingspy/tests/MyModelicaLibrary/package.mo, buildingspy/tests/MyModelicaLibrary/package.order, buildingspy/tests/test_development_refactor.py
=> Updated bugfix for generation of package.order for #189

buildingspy/development/regressiontest.py
=> Improved error message for #191

buildingspy/CHANGES.txt, buildingspy/development/refactor.py
=> Issue193 move class

buildingspy/development/refactor.py
=> Added rewrite of package.order

buildingspy/CHANGES.txt, buildingspy/development/merger.py
=> Added wildcard support in merge, and filtered files

buildingspy/development/regressiontest.py
=> Changed exit for #214

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py, buildingspy/tests/test_development_regressiontest.py
This closes #213 and includes https://github.com/lbl-srg/BuildingsPy/pull/216
=> Issue213 ignored variables

buildingspy/CHANGES.txt, buildingspy/development/refactor.py
=> Corrected handling of package.order files for #229

.travis.yml, Makefile, buildingspy/development/refactor.py, buildingspy/development/regressiontest.py, buildingspy/development/validator.py, buildingspy/examples/dymola/plotResult.py, buildingspy/io/outputfile.py
This closes #237 
@thorade : can you please review, not sure why `autopep8` suddenly added `r` to denote literal strings, see https://travis-ci.org/lbl-srg/BuildingsPy/jobs/474643741#L736
=> Issue237 autopep8

.travis.yml, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/dymola
=> Changed image name

buildingspy/development/regressiontest.py
This closes #246 
@Mathadon : Does this address it?
=> Issue246 delay error

buildingspy/development/error_dictionary_dymola.py, buildingspy/development/regressiontest.py, buildingspy/tests/test_development_error_dictionary.py
This closes https://github.com/lbl-srg/BuildingsPy/pull/248
This closes #203
=> Issue203 count

buildingspy/development/merger.py
=> Micha mans issue66 reffiles

buildingspy/CHANGES.txt, buildingspy/development/merger.py, buildingspy/tests/test_development_merger.py
=> Issue259 library specific comments

buildingspy/development/error_dictionary_jmodelica.py, buildingspy/development/regressiontest.py, buildingspy/tests/test_development_regressiontest_jmodelica.py
=> Removed warning for missing start value on iteration variable for JModelica

.travis.yml, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/jm_ipython.sh
=> Updated docker image for #263

buildingspy/development/merger.py
=> Excluded ConvertIBPSA_from_*.mos from merge

buildingspy/development/validator.py, buildingspy/tests/test_development_Validator.py
=> Issue265 integer overflow

Makefile, buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py, buildingspy/license.txt, doc/source/conf.py, doc/source/legal.rst
=> Issue270 release2 0 0

buildingspy/CHANGES.txt, buildingspy/development/merger.py
=> Issue272 merge binary files

.travis.yml, buildingspy/development/regressiontest.py, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/dymola
=> Issue276 run simulation

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py
=> Issue274 file name length

buildingspy/development/regressiontest.py
This closes https://github.com/lbl-srg/BuildingsPy/pull/297
This closed #296
=> Mathadon issue296 error reporting

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py
This closes #304 
This closes #303
=> Issue303 work dir and dde

buildingspy/CHANGES.txt, buildingspy/development/jmodelica_run.template
=> Issue301 nle solver

buildingspy/CHANGES.txt, buildingspy/development/merger.py, buildingspy/development/regressiontest.py, buildingspy/tests/MyModelicaLibrary/Obsolete/Constant.mo, buildingspy/tests/MyModelicaLibrary/Obsolete/Examples/Constant.mo, buildingspy/tests/MyModelicaLibrary/Obsolete/Examples/package.mo, buildingspy/tests/MyModelicaLibrary/Obsolete/Examples/package.order, buildingspy/tests/MyModelicaLibrary/Obsolete/package.mo, buildingspy/tests/MyModelicaLibrary/Obsolete/package.order, buildingspy/tests/MyModelicaLibrary/Resources/ReferenceResults/Dymola/MyModelicaLibrary_Obsolete_Examples_Constant.txt, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/Dymola/Obsolete/Examples/Constant.mos, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/OpenModelica/compareVars/MyModelicaLibrary.Obsolete.Examples.Constant.mos, buildingspy/tests/MyModelicaLibrary/package.order, buildingspy/tests/test_development_regressiontest.py
=> Issue308 obsolete models

.travis.yml, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/dymola
=> Updated files for dymola 2020x

buildingspy/development/jmodelica_run.template, buildingspy/io/postprocess.py, buildingspy/tests/test_io_postprocess.py
@mwetter It's ready for your review. Following changes have been done to ensure Python3 and 2 compatibility:
=> Issue314 python3

buildingspy/development/regressiontest.py
=> Added check whether stdout exists

buildingspy/development/jmodelica_run.template
=> Changed getting exception message.

buildingspy/CHANGES.txt, buildingspy/development/error_dictionary_jmodelica.py, buildingspy/development/error_dictionary_optimica.py, buildingspy/development/optimica_run.template, buildingspy/development/optimica_run_all.template, buildingspy/development/regressiontest.py, buildingspy/development/validator.py, buildingspy/tests/test_development_Validator.py, buildingspy/tests/test_development_regressiontest_optimica.py
=> Issue324 optimica ci

buildingspy/development/regressiontest.py, buildingspy/io/outputfile.py
=> Corrected handling of tests for optimica

buildingspy/development/regressiontest.py
=> Corrected indentation which caused error count to be not increased

buildingspy/development/regressiontest.py
=> Issue330 optimica ci

buildingspy/templates/datatable.html, buildingspy/templates/plot.html
=> Issue332 html plot

.travis.yml, Makefile, buildingspy/CHANGES.txt, buildingspy/development/merger.py, buildingspy/development/regressiontest.py, buildingspy/io/outputfile.py, buildingspy/io/postprocess.py, buildingspy/simulate/Simulator.py
=> Issue336 doctest 3.6

buildingspy/CHANGES.txt, buildingspy/development/refactor.py, buildingspy/tests/test_development_refactor.py
=> Preserved ordering of constants

buildingspy/development/regressiontest.py
=> Put current working directory in front of MODELICAPATH

buildingspy/development/regressiontest.py
=> added support for new translation statistics

.travis.yml, buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py, buildingspy/io/postprocess.py
=> Issue343 count models

buildingspy/development/jmodelica_run.template
=> Removed setting for maximum step size in optimica

buildingspy/development/error_dictionary_dymola.py, buildingspy/tests/test_development_error_dictionary.py
=> Added test for suspicious min/max

README.rst, buildingspy/development/refactor.py
=> Issue364 instruction

buildingspy/development/merger.py
This includes pyc to exclude list of the merger method.
=> Added pyc to exclude list.

buildingspy/tests/test_simulate_Dymola.py
This corrects the arguments for dymola in the regression tests.
=> Corrected arguments

buildingspy/development/refactor.py, buildingspy/development/regressiontest.py, buildingspy/tests/test_development_refactor.py
This closes #382 
This is ready to merge when all tests pass.
=> Fix refactor.move_class

buildingspy/CHANGES.txt, buildingspy/development/refactor.py, buildingspy/tests/test_development_refactor.py
=> Issue387 package.order

buildingspy/simulate/base_simulator.py
This corrects the error handling if the executable for the Modelica environment is not found.
=> Corrected error handling

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py
=> Added optional comment to conf.json #389

Makefile, buildingspy/CHANGES.txt, buildingspy/development/jmodelica_run.template, buildingspy/development/optimica_run.template, buildingspy/simulate/Dymola.py, buildingspy/simulate/Optimica.py, buildingspy/simulate/base_simulator.py, buildingspy/tests/MyModelicaLibrary/MyModelTimeOut.mo, buildingspy/tests/MyModelicaLibrary/Resources/C-Sources/MySleep.c, buildingspy/tests/MyModelicaLibrary/package.order, buildingspy/tests/test_simulate_Dymola.py, buildingspy/tests/test_simulate_Optimica.py, setup.py
=> Issue385 timeout

buildingspy/CHANGES.txt, buildingspy/simulate/Optimica.py, buildingspy/tests/test_simulate_Dymola.py, buildingspy/tests/test_simulate_Optimica.py
This closes #397 
This allows running simulations in different directories
=> Updated the code for use with multiprocessing

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py
=> Set Advanced.GenerateVariableDependencies = false

buildingspy/CHANGES.txt, buildingspy/development/merger.py
=> Issue412 library name merger

buildingspy/simulate/Dymola.py, buildingspy/simulate/Optimica.py, buildingspy/simulate/base_simulator.py, buildingspy/tests/test_examples_dymola.py, buildingspy/tests/test_simulate_Dymola.py, buildingspy/tests/test_simulate_Optimica.py
=> Issue414 optimica translate

buildingspy/simulate/Dymola.py, buildingspy/simulate/Optimica.py, buildingspy/simulate/base_simulator.py
This removes python 2 constructs that are no longer needed.
=> Removed python2 constructs

buildingspy/CHANGES.txt, buildingspy/development/error_dictionary_optimica.py
This closes #424.
It can be merged after
https://github.com/lbl-srg/modelica-buildings/pull/2472
and
https://github.com/lbl-srg/modelica-buildings/pull/2473
=> Issue424 check access

buildingspy/development/merger.py
Added pyc to exclude list, corrected arguments in _copy_rename call
=> Fixed merge script

.travis.yml, buildingspy/tests/MyModelicaLibrary/Resources/Scripts/travis/bin/jm_ipython.sh
This sets the python requirement from 3.6.9 to 3.6
=> Set python to 3.6

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py
=> Issue451 colored output

.travis.yml, requirements.txt
See https://github.com/lbl-srg/BuildingsPy/security/dependabot/requirements.txt/jinja2/open
=> Updated Jinja2

buildingspy/development/openmodelica_run.template, buildingspy/development/regressiontest.py
=> Changed solver to dassl as default

buildingspy/development/regressiontest.py
This disables color output on windows.
=> Patch color output

buildingspy/development/regressiontest.py
This fixes a bug that avoided time series from Dymola to be verified.
=> Patch check condition dymola

buildingspy/development/regressiontest.py
This corrects the message displayed to the user. It specifies the tool that has been used to run the unit tests
=> Corrected screen output to invoke correct result comparison

buildingspy/development/regressiontest.py
This changes the color output during regression tests if only statistics changed but the results are the same. This makes it easier to quickly indicate changes
=> Changed color output

buildingspy/development/regressiontest.py
This is a patch for https://github.com/lbl-srg/BuildingsPy/pull/509
=> Corrected dictionary access

.travis.yml
This adds new versions for the docker images
=> This updates the images for the CI test

buildingspy/CHANGES.txt, buildingspy/simulate/base_simulator.py
This closes https://github.com/lbl-srg/BuildingsPy/pull/517
It revises the implementation slightly without changing the behavior.
=> Patch gitsdfawfevi moe files

buildingspy/CHANGES.txt, buildingspy/simulate/base_simulator.py
This closes https://github.com/lbl-srg/BuildingsPy/pull/518
=> Patch modelica path

buildingspy/CHANGES.txt, requirements.txt, setup.py
This changes the version date and updates gitpython
=> Changed version date

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py
=> Corrected bug if reference file is missing

.travis.yml, setup.py
This adds changes for https://github.com/lbl-srg/BuildingsPy/pull/533
=> Increase minimum version of Jinja2

buildingspy/development/regressiontest.py
This removes a left-over debug output.
=> Removed debug output

requirements.txt, setup.py
Update dependency versions.
This integrates https://github.com/lbl-srg/BuildingsPy/pull/547
=> Compatibility with newer Python versions

buildingspy/development/merger.py
@mwetter This commit fixes the merge issues on our CI and works locally just as before.
Closes #554
=> fix join operation error

buildingspy/development/merger.py
=> fix join operation error (#555)

buildingspy/CHANGES.txt, buildingspy/development/merger.py, buildingspy/tests/test_development_merger.py
This closes #566
@FWuellhorst : See the changes to the PR.
=> Added code to exclude certain Modelica code during merge

buildingspy/CHANGES.txt, buildingspy/development/simulationCompare.py
=> Issue568 simulation compare verification

.travis.yml
This updates the docker images of oct, omc and dymola to recent versions.
=> Update docker images

buildingspy/CHANGES.txt, buildingspy/simulate/base_simulator.py
=> Corrected error reporting statement

buildingspy/CHANGES.txt, buildingspy/development/openmodelica_run.template, buildingspy/development/regressiontest.py, buildingspy/simulate/OpenModelica.py
=> For OpenModelica, use setModelicaPath to point to other libraries that may need to be loaded

buildingspy/CHANGES.txt, buildingspy/development/openmodelica_run.template, buildingspy/development/regressiontest.py, buildingspy/simulate/OpenModelica.py, buildingspy/tests/test_simulate_OpenModelica.py
This closes #585
This is based on #587
=> Issue585 omc set number of intervals

.travis.yml
=> Updated oct image to 1.55.11

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py, buildingspy/simulate/Dymola.py, buildingspy/simulate/base_simulator.py
=> Changed code to use dmc rather than dymola

buildingspy/development/openmodelica_run.template, buildingspy/development/regressiontest.py, buildingspy/simulate/OpenModelica.py
=> Added loadFile for OpenModelica CI tests

.travis.yml
This updates the dymola image.
=> Update dymola image
