lbl-srg/BuildingsPy

buildingspy/development/refactor.py
add the top level directory to the list of directories that will be checked in non-recursive mode.
this fixes #58
=> if the set s is not empty,

.gitignore, buildingspy/examples/dymola/case1/.gitignore, buildingspy/examples/dymola/case2/.gitignore, buildingspy/examples/dymola/runSimulationTranslated.py, buildingspy/io/outputfile.py, buildingspy/simulate/Simulator.py, buildingspy/tests/test_simulate_Simulator.py, src/.gitignore
I replaced the call `_deleteTemporaryDirectory` by a public method. Also two tests were added to check for (1) if parameters were actually changed after `translate` and (2) if an error occured during simulation and if so the error is send to the reporter.
=> Issue70 simulation: test for parameter changes and simulation errors

buildingspy/development/error_dictionary.py, buildingspy/development/merger.py, buildingspy/development/refactor.py, buildingspy/development/regressiontest.py, buildingspy/development/validator.py, buildingspy/examples/dymola/plotResult.py, buildingspy/io/outputfile.py, buildingspy/io/postprocess.py, buildingspy/io/reporter.py, buildingspy/simulate/Simulator.py, buildingspy/tests/test_development_error_dictionary.py, buildingspy/tests/test_development_refactor.py, buildingspy/tests/test_development_regressiontest.py, buildingspy/tests/test_io_postprocess.py
This is for #94, it is the output from `futurize --stage2 -w *.py`,
with some manual tweaks: old_div was not used, true float div was used everywhere.
`make doctest` still passes on Python 2, and still fails in Python 3.
For testing, use `python2` or `python3` instead of just `python` in the makefile.
`make unittest` fails for me before and after.
This PR adds some new imports from the pip installable package `future`, 
so it will add `future` to the dependencies (for Python 2 users).
ToDo:  mention future as dependency in  setup.py
http://python-future.org/compatible_idioms.html#setup
http://python-future.org/compatible_idioms.html#range
This PR also covers everything that was proposed in #93.
Search for `iteritems` in #93 and here: …
=> Issue94 futurize 2nd

.travis.yml, buildingspy/development/merger.py, buildingspy/tests/test_development_merger.py
This should close #119.
The command
```
python buildingspy/tests/test_development_merger.py
```
works for me on Linux, before and after.
On Windows 10 it failed before and after with the error message
```
error: unable to create file Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DistrictHeatingCooling.SubStations.VaporCompression.Validation.HeatingCoolingHotwaterTimeSeries_dT.mos: Filename too long
```
=> shallow clone

.travis.yml, buildingspy/fmi/__init__.py
`system_site _packages` should only be used if necessary:
https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
But here it is not necessary, because scipy and numpy are easily installed via pip.
By using `only-binary` it is as quick as apt-get, but it will work on any Python version.
MPLBACKEND is for matplotlib.
Does this Pull Request trigger a build?
https://travis-ci.org/lbl-srg/BuildingsPy/pull_requests
docker will only work inside this repository, not on forks.
=> Test ci py3

buildingspy/development/regressiontest.py, buildingspy/tests/test_development_regressiontest.py
Added option to pass for regression tests the package list in notation such as `A.{B, C, D}`.
=> Added option to pass packages in notation A.{B,C}

buildingspy/development/regressiontest.py
Commit b369acc7a5ef6fd95e86dd0529eded2f14cd4da7 (part of #140 and #94) broke the input for accepting reference results.
Python 2 knows `raw_input` and `input`, where `raw_input` always returns a string and `input` is identical to  `eval(raw_input)`.
Python 3 only knows `input` and it behaves like `raw_input` did on Py2, because a string is what most people wanted and using eval is a security problem. 
The futurize script does not know whether the `eval` step was really needed and adds it, but that does not work here: it is treating the input `Y` as a variable and tries to evaluate it, but there is no variable named `y` so one gets a `NameError: name Y is not defined`.
As we really wanted a string anyway, `raw_input` would have been correct in Py2 and `input` would have been correct on …
=> fix reference results acceptance

.travis.yml, buildingspy/development/regressiontest.py
because it will be more easy to see which one failed
do not install dependencies in travis, instead define them in setup.py
this way one can test whether the setup.py file is complete
=> split doctest and unittest,

buildingspy/development/regressiontest.py
dump writes to the logFil directly,
while dumps writes into a string, and then we use logFil.write(string)
this is a correction of
https://github.com/lbl-srg/BuildingsPy/commit/c80adf719617ff99811f6e0d5fd2b444ff2d1e03?w=1
detected, because Py3.6 allows only 1 positional argument for json.dumps (all other arguments have to be kwargs).
=> only 1 positional argument for json.dumps

buildingspy/development/regressiontest.py
This removes the message "No package specified or no unit test found for the specified package. All unit tests of the root package will be run." which is not needed.
=> Removed non-needed console output.

.travis.yml, doc/source/install.rst, requirements.txt, setup.py
This closes #370 and #371 trough funnel [#44](https://github.com/lbl-srg/funnel/pull/44), [#46](https://github.com/lbl-srg/funnel/pull/46) and [#48](https://github.com/lbl-srg/funnel/pull/48).
Please note that installation instructions for development (in `doc/source/install.rst`) have been updated to use `requirements.txt` instead of manually installing pyfunnel.
```rst
To clone BuildingsPy for development, run
.. parsed-literal::
git clone git@github.com:lbl-srg/BuildingsPy.git
cd BuildingsPy
python3 -m pip install --user -r requirements.txt
```
=> Issue371 pyfunnel dist

buildingspy/io/reporter.py
This fixes a race condition that occurred when running:
```python
import os
from multiprocessing import Pool
from buildingspy.simulate.Dymola import Simulator
from buildingspy.io.outputfile import Reader
#Buildings.ThermalZones.Detailed.Validation.SingleZoneFloorWithHeating
cases = [ \
{"model": "Buildings.ThermalZones.Detailed.Validation.SingleZoneFloorWithHeating", "solver": "Radau",  "tol": 1E-6},
{"model": "Buildings.ThermalZones.Detailed.Validation.SingleZoneFloorWithHeating", "solver": "Radau",  "tol": 1E-7},
{"model": "Buildings.ThermalZones.Detailed.Validation.SingleZoneFloorWithHeating", "solver": "Radau",  "tol": 1E-8},
{"model": "Buildings.ThermalZones.Detailed.Validation.SingleZoneFloorWithHeating", "solver": "Cvode",  "tol": 1E-6},
{"model": …
```
=> Fixed race condition

buildingspy/development/regressiontest.py
This excludes more files from being copied during the regression tests.
=> Excluded files from being copied during regression tests

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py, buildingspy/io/postprocess.py, buildingspy/tests/test_development_regressiontest.py, requirements.txt
This closes #408 
Bumps [jinja2](https://github.com/pallets/jinja) from 2.11.1 to 2.11.3.
- [Release notes](https://github.com/pallets/jinja/releases)
- [Changelog](https://github.com/pallets/jinja/blob/master/CHANGES.rst)
- [Commits](https://github.com/pallets/jinja/compare/2.11.1...2.11.3)
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump jinja2 from 2.11.1 to 2.11.3

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py
=> Avoided copying .mat and .log files in CI tests

buildingspy/development/merger.py
This adds the files `status` and `success` to the exclude list of the merger.
=> Added Dymola temporary files to exclude list in merger

buildingspy/development/refactor.py
This fixes a bug in the refactor script that causes a run-time error due to running git add on a file that does not yet exist.
=> Corrected bug in git add that was run on a file that does not yet exist

buildingspy/development/regressiontest.py
This avoids asking the user to accept new reference results if the unit tests are run in batch mode.
=> Avoided asking user to accept new reference results if run in batch mode

buildingspy/development/regressiontest.py
This fixes a bug that causes to ignore N if a reference result file does not yet exist
=> Fixed bug that ignored N when reference results do not yet exist

buildingspy/development/merger.py
This reflects the new location of the conversion script which moved from Dymola to Conversion
=> Updated location of conversion script

buildingspy/development/merger.py
This also avoids merging buildlog.txt
=> Excluded all txt file in top-level package from merging

buildingspy/CHANGES.txt, buildingspy/development/refactor.py
=> Corrected bug that causes renames to fail on Windows

buildingspy/io/outputfile.py
When a dymola simulation fails, python throws an IndexError: string index out of range instead of proper error reporting.
```
Traceback (most recent call last):
File "C:\Program Files\Python\Python311\Lib\multiprocessing\pool.py", line 125, in worker
result = (True, func(*args, **kwds))
^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python\Python311\Lib\multiprocessing\pool.py", line 48, in mapstar
return list(map(*args))
^^^^^^^^^^^^^^^^
File "C:\Users\calculator\Desktop\VehicleTES\Simulate_SystemOverview_MinMax.py", line 21, in simulateCase
s.simulate()
File "C:\Program Files\Python\Python311\Lib\site-packages\buildingspy\simulate\Dymola.py", line 287, in simulate
self._check_simulation_errors(worDir)
File "C:\Program Files\Python\Python311\Lib\site-packages\buildingspy\simulate\Dymola.py", …
```
=> Fix IndexError: string index out of range

.travis.yml, buildingspy/CHANGES.txt, buildingspy/io/outputfile.py
This corrects a `string index out of range` due to access of the wrong data structure.
This closes #536
=> Correct error message if dymola has a simulation error

requirements.txt, setup.py
Installing with Python >= 3.10 is not possible "out-of-the-box"
[It seems there is an issue with PyYAML not being compatible with Cython >= 3](https://github.com/yaml/pyyaml/issues/724)
Installing PyYAML 6.0.1 instead solves the issue (tested with a fresh install of Python 3.10.14 and Python 3.12.3)
[PyYAML changes:](https://github.com/yaml/pyyaml/blob/main/CHANGES)
6.0.1 (2023-07-18)
* https://github.com/yaml/pyyaml/pull/702 -- pin Cython build dep to < 3.0
6.0 (2021-10-13)
* https://github.com/yaml/pyyaml/pull/327 -- Change README format to Markdown
* https://github.com/yaml/pyyaml/pull/483 -- Add a test for YAML 1.1 types
* https://github.com/yaml/pyyaml/pull/497 -- fix float resolver to ignore `.` and `._`
* https://github.com/yaml/pyyaml/pull/550 -- drop Python 2.7
* …
=> Compatibility with newer Python versions

buildingspy/CHANGES.txt, buildingspy/development/refactor.py
It is possible to change the directory of `DHC` from `Buildings.Experimental.DHC` to `Buildings.DHC` thanks to the function `move_class`. During the process, the images are moved recursively via the function `_move_class_directory` that calls for each folder the function `_move_images_directory`. To move the folders, the command line `git mv` is used.
For example, the package `Buildings. Experimental .DHC.EnergyTransferStations.Combined` has 2 images, `PartialParallel` and `ChillerBorefield`. 
During the first iteration, for `BaseClasses.PartialParallel`, `Resources\Images\Experimental\DHC\EnergyTransferStations\Combined\BaseClasses` is moved to `Resources\Images\DHC\EnergyTransferStations\Combined\BaseClasses`, which is the expected behavior.
BUT during the second iteration for …
=> Problem copying images

buildingspy/development/merger.py
This exludes the .bak-mo from being merged
=> Exclude .bak-mo from merging

buildingspy/CHANGES.txt, buildingspy/development/error_dictionary_optimica.py
This catches the Optimica warnings of the form 'Integer literal "7347600000" is too large to represent as 32-bit'
=> Added check for integer being too large in Optimica CI tests

buildingspy/development/regressiontest.py, buildingspy/tests/test_development_regressiontest.py
This closes #253 and addresses the review in #307 . 
@mwetter : Could you do the review?
=> Issue253 coverage

buildingspy/development/regressiontest.py
Closes #560 
@mwetter : 
- I tried to look for tests where new results are generated, but found None. If you have one, I could write a case with `createNewReferenceResultsInBatchMode=True`. 
- As it is linked to batchMode, I went for the same "set"-method. 
- This PR has some debugging commits, feel free to squash and merge this.
=> Enable creation of new reference results in batch mode

buildingspy/CHANGES.txt, buildingspy/development/regressiontest.py
* add options for startup and additional package loading
=> Enable creation of new reference results in batch mode (#561)

buildingspy/development/regressiontest.py
Closes #579 
I used `ValueError` as raising a UnicodeDecodeError requires more inputs, see https://gehrcke.de/2015/12/how-to-raise-unicodedecodeerror-in-python-3/.
Raising "from" should also show the old error.
=> fix file ending, re-raise error with better message

buildingspy/development/regressiontest.py
=> fix file ending, re-raise error with better message (#580)
